modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="carriagefix"
version="1.0.0"
displayName="Carriage Render Fix"
authors="DeepSeek & Chase_meng"
description="修复 Create 0.5.1.j 车门大范围开闭时的掉帧问题"
logoFile="icon.png"

[[dependencies.carriagefix]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.carriagefix]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1)"
ordering="NONE"
side="CLIENT"

[[dependencies.carriagefix]]
modId="create"
mandatory=true
versionRange="[0.5.1,0.5.2)"
ordering="NONE"
side="CLIENT"